[package]
name = "codes"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.228"
serde_json = "1.0.148"
bincode = "1"
serde_cbor = "0.8"
serde_derive = "1"
byteorder = "1.5.0"
crc = "3.4.0"
